### ISSUE TITLE
Tomcat module fails during installation

### ISSUE THREAD

**Issue by pct960** [rbccps-iisc/smartcity-middleware-docker#13]
The tomcat module fails during the middleware installation. However, when the installation is limited to tomcat using

    python smartcity-middleware.py install -f middleware.conf -l tomcat
It succeeds. It has now become necessary to do this as the tomcat installation fails every single time the middleware installation is carried out.

**Comment by harishanand95** [comment]
@pct960 Does this issue still occur? 
Could you attach the logs here.

**Comment by pct960** [comment]
No, it doesn't. It surprisingly succeeds during the initial installation process. However, the cause needs to be isolated and taken care of. I think it was after https://github.com/rbccps-iisc/smartcity-middleware-docker/commit/d83c2da8ae0b7db17ab39fb06e1d5661d7339405 that it started working properly
